### PR TITLE
Feature/ui

### PR DESCRIPTION
**Pull request by duykhoa**
UI for blog, still have some small bugs (will fix in next iterations)

@vinhnglx: Please help me review this PR :heart_eyes:

### CODE REVIEW

**Comment by vinhnglx** [comment]
80 commits :+1:  @duykhoa

**Comment by vinhnglx** [comment]
@duykhoa awesome. The source from https://github.com/jollygoodcode/jollygoodcode.github.io

blackhulk

**Comment by vinhnglx** [comment]
@duykhoa please display `blog_title` and `blog_description`. Haha. I don't know how to show

**Comment by vinhnglx** [comment]
@duykhoa LGTM ... But we need to display the title and description before first release ^^

**Comment by duykhoa** [comment]
@vinhnglx Let me handle that man :+1:

**Comment by duykhoa** [comment]
@vinhnglx: no idea why there are blog_title & blog_setting attributes, but only blog_title attribute is loaded when enter localhost:3000 on the browser. :trollface:

**Comment by vinhnglx** [comment]
@duykhoa :+1:  :100:  will merge it.

**Comment by duykhoa** [comment]
Pls go ahead :laughing:

**Pull request merged**
